### ISSUE TITLE
Highlight.js dependencies missing

### ISSUE THREAD

**Issue by tim-hilde** [davidar/pandoc-lang#1]
When trying to install pandoc-lang I get the following error:

`npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest`

From my understand, this means you have to update the dependencies

**Comment by tim-hilde** [comment]
Thank you for the fix, but I don't see this reflected when trying to install it

**Comment by davidar** [comment]
I've published a new version to npm just now
